global:
    loglevel: "DEBUG"
databases:
    marketdata:
        schema: ""
        user: ""
        password: ""
        host: ""
    marketdw:
        schema: ""
        user: ""
        password: ""
        host: ""
        chunk_size: 100000
datasources:
    IEX:
        key: ""
        url: "https://cloud.iexapis.com/stable"
    AlphaVantage:
        key: ""
        url: "https://www.alphavantage.co/query?function="
        obs: 30
    SymbolList:
        nasdaq: "ftp://ftp.nasdaqtrader.com/symboldirectory/nasdaqlisted.txt"
        other: "ftp://ftp.nasdaqtrader.com/symboldirectory/otherlisted.txt"
