databases:
    marketdata:
        schema: ""
        user: ""
        password: ""
        host: ""
    marketdw:
        schema: ""
        user: ""
        password: ""
        host: ""
        chunk_size: 10000
datasources:
    AlphaVantage:
        key: ""
        url: "https://www.alphavantage.co/query?function="
        obs: 30
    IEX:
        key: ""
        url: "https://cloud.iexapis.com/stable/"
    SymbolList:
        nasdaq: "https://datahub.io/core/nasdaq-listings/r/nasdaq-listed-symbols.csv"
        nyse: "https://datahub.io/core/nyse-other-listings/r/nyse-listed.csv"
